version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/main
      args:
        VITE_BACKEND_API_URL: /api
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    hostname: backend
    ports:
      - "5000:5000"
